### ISSUE TITLE
The check for Aeonic ranged weapons is performed when no ranged weapons is equipped

### ISSUE THREAD

**Issue by benbou8231** [Ivaar/Skillchains#10]
When no ranged weapon is equipped, the check for Aeonic ranged weapons raise an error because a nil value is passed to get_items at line #142 of Skillchains.lua.

**Comment by Ivaar** [comment]
Was it a nil value being passed or did windower.ffxi.get_items return nil

**Comment by Ivaar** [comment]
I'm unable to reproduce this by equipping and removing a ranged weapon,

**Comment by Ivaar** [comment]
Seems I fixed this on my local copy, pushing those changes now. Thanks!
