### ISSUE TITLE
Add detection for Siren BP

### ISSUE THREAD

**Issue by blackfiveo** [Ivaar/Skillchains#11]
Doesnt seem to detect the new bp99 Siren

**Comment by Ivaar** [comment]
I will need someone to confirm skillchain properties

**Comment by blackfiveo** [comment]
Hysteric Assault
Skillchain | Fragmentation
Skillchain2 Transfixion
(also not sure but worth mentioning  Hysteric Assault appears to be more of a "Convert Damage to HP" than a Drain.)


Roundhouse:
Detonation

Welt:
Scission

**Comment by blackfiveo** [comment]
Thanks!
