### ISSUE TITLE
Jumps don't skillchain

### ISSUE THREAD

**Issue by klikevil** [Ivaar/Skillchains#13]
The plugin is counting jumps as a weaponskill and says you can close with relic ws or cam torment...  You can't

**Comment by Ivaar** [comment]
This was likely caused by junk added effect data in the action packet and should now be fixed. I noticed this in my data collection logs and tried to reproduce it over a week ago. Since it was caused by a random passerby and I wasn't recorded packets, I could not verify what I needed. Can you confirm your version number and see if it still occurs in the latest version?

**Comment by klikevil** [comment]
Current: 
```

Administrator@period ~/Administrator/addons/Skillchains
$ grep -i version Skillchains.lua 
_addon.version = '2.20.08.08'

```

```
Administrator@period ~/Administrator/addons/Skillchains
$ git log --color=always|& head
commit dd7a7c084be7e99c713c8ecfb9a0f8a78410451e
Author: Ivaar <7287342+Ivaar@users.noreply.github.com>
Date:   Sat Aug 15 04:15:30 2020 -0700

    Skillchains: all trust attributes verified, blue spells amended

```


Just pulled the most recent

```

Administrator@period ~/Administrator/addons/Skillchains
$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/Ivaar/Skillchains
   dd7a7c0..7d68a2c  master     -> origin/master
Updating dd7a7c0..7d68a2c
Fast-forward
 Skillchains.lua |  4 ++--
 skills.lua      | 49 +++++++++++++++++++++----------------------------
 2 files changed, 23 insertions(+), 30 deletions(-)

```

Will test with this one now:
```

Administrator@period ~/Administrator/addons/Skillchains
$ !grep
grep -i version Skillchains.lua 
_addon.version = '2.20.08.17'


```

**Comment by klikevil** [comment]
It is not fixed in this most recent version

**Comment by Ivaar** [comment]
You mentioned relic weaponskill, does it happen without Gugnir equipped? Can you give any additional information/steps to reproduce?

**Comment by Ivaar** [comment]
If you're able to get a packet capture, it would really help. Load [packetviewer ](https://github.com/z16/Addons/tree/master/PacketViewer) and use this tracking command `//pv t i 0x28 Category 3;pv rec` perform a jump and screenshot it.

**Comment by klikevil** [comment]
![img_20200818_230631](https://user-images.githubusercontent.com/32278206/90587522-9abbac00-e1a7-11ea-885f-4d45fbef0488.png)
Hope this is good enough, appears to be caused by relic reforge body +3 that does additional damage 100% of wyvern's hp; still occurs with relic weapon unequipped but only shows camlann's torment seems to unequivocally be caused by this Ptero. Mail +3's additional effect appearing like a weapon skill I suppose?

**Comment by klikevil** [comment]
Appears to be caused by relic reforge body +3 that does additional damage 100% of wyvern's hp.

**Comment by Ivaar** [comment]
That rules out junk effects, which should all be filtered. I couldn't find anything on the wikis that gave jump an added effect and actually displayed a message. Thank you for verifying that.

**Comment by klikevil** [comment]
Line 365 displays a runtime error when i perform jumps now saying it got a null value and sometimes it is ignoring weaponskills after the first one.  [This is the link to the armor](https://www.bg-wiki.com/bg/Ptero._Mail_%2B3)  Not sure if I should make a new issue for that or leave this one open because it's likely still related due to the runtime error in skillchain_ids

![img_20200819_100056](https://user-images.githubusercontent.com/32278206/90644848-3af2ee80-e203-11ea-9e8c-4d14ff45a9b7.png)

**Comment by Ivaar** [comment]
Pushed a fix, was a late night typo. Sorry for any inconvenience.

**Comment by klikevil** [comment]
That got it, and no problem I appreciate your hard work and quick turn around time, thanks!
