### ISSUE TITLE
Modifications etc

### ISSUE THREAD

**Issue by SammehFFXI** [Ivaar/Skillchains#2]
Ivaar - I've added / customized some of your code last night.  (My coding skills aren't what yours are - this is *very* clean).

Anyway - I wanted to make sure pets were more represented as skillchains (specifically jug pets).  While they were recorded - if you were BST main it didn't show your pets abilities to continue the chain.  Only main hand weaponskills.

Also - I added some color to it.

Do you want me to do a pull/merge?  

Also - can you release it under normal windower license for redistribution/modification?

`--[[
Copyright © 2016, <<CharName>> of <<Server>>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of <<ADDON_NAME>>nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <<CHARNAME>> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
`

**Comment by Ivaar** [comment]
Added license, go for it, I'd like to see what you have. There's a lot that needs to be done, unfortunately I don't think I'll be able to put the time I need into finishing this. I'll try to get on the game this month and check things out.

**Comment by SammehFFXI** [comment]
ok I apparently have *no* idea how to use GIT properly hahaha ;)

See if you can see this under forks anywhere etc.  If not direct link is:
https://github.com/SammehFFXI/Skillchains

**Comment by SammehFFXI** [comment]
Updated from a couple of days ago.  I added in Aeonic Aftermath values based on having the aftermath.  I thought about making an actual 'radiance' chain but ultimately its the same thing as a lvl 4 skillchain. Hope this is helpful.

**Comment by Ivaar** [comment]
I will add your modifications to my repository soon, I'll also be making changes and fixing bugs over the next few weeks.

**Comment by Ivaar** [comment]
I've added your modifications to my repository. I disabled the colors on weapon skills, the dark blue on black background is hard on the eyes, I'll check it out later.

**Comment by Ivaar** [comment]
There's now a toggle for aeonics to add respective property to merit weapon skills used by all players other than yourself. Perhaps a list to track your buddies who own aeonics would be useful. I think I've done all I can with it at this point, can you verify that aeonics are being handled properly. I plan on adding it to the windower repo once I have decided on a structure for the settings.
