### ISSUE TITLE
I have not been able to make the addon work

### ISSUE THREAD

**Issue by ralonsodeniz** [Ivaar/Skillchains#3]
Hello,
I have been trying to make this addon work but I have failed. I have added it to the addon folder and added  <addon>SkillChains</addon> in the settings.xml but the addon does not load when I start FFXI. Could someone tell me what I am missing? 
Thank you and sorry about the inconvenience.

**Comment by SammehFFXI** [comment]
You'll need to do a //lua load skillchains and add that to your init startup .   BTW you can check out the additions I've made to this https://github.com/SammehFFXI/Skillchains

**Comment by ralonsodeniz** [comment]
Understood, thank you so much. I am using your version, I tried to post the question at your GitHub but I was unable to post an issue there, I'm new to this too.
