### ISSUE TITLE
Error on newest version

### ISSUE THREAD

**Issue by bluethunder1080** [Ivaar/Skillchains#4]
Hi,

getting an error on the newest version posted

skillchains.lua:382 attempt to call_global 'update_weapon' a nil value

any help is appreciated, thanks

**Comment by Ivaar** [comment]
Sorry, I had copy/pasted some performance enhancements from the next unreleased version, where I altered some function names. I've now changed them back. Thanks for the alert

**Comment by bluethunder1080** [comment]
Thank you ^.^
